### ISSUE TITLE
utils.py  ERROR  ERROR! Unexpected Exception, this is probably a bug: 'webhook_url'

### ISSUE THREAD

**Issue by jpopelka** [TomasTomecek/ansible-bender#76] opened 2019-02-28 10:28 UTC
From https://ci.centos.org/job/packit-pr/27/console

```
11:24:08  Writing manifest to image destination
11:24:08  Storing signatures
11:24:35  81174df11aeb5baf4ecf69d936b72c329d2ec3d3becec52f07caeeb414cab3f2
11:24:36   [WARNING]: Skipping plugin (/usr/local/lib/python3.6/site-
11:24:36  packages/ansible_bender/callback_plugins/snapshoter.py) as it seems to be
11:24:36  invalid: invalid syntax (buildah_builder.py, line 262)
11:24:36   [WARNING]: The `prettytable` python module is not installed. Disabling the
11:24:36  10:24:35.946 utils.py          ERROR   [WARNING]: Skipping plugin (/usr/local/lib/python3.6/site-
11:24:36  10:24:35.947 utils.py          ERROR  packages/ansible_bender/callback_plugins/snapshoter.py) as it seems to be
11:24:36  10:24:35.947 utils.py          ERROR  invalid: invalid syntax (buildah_builder.py, line 262)
11:24:36  10:24:35.948 utils.py          ERROR   [WARNING]: The `prettytable` python module is not installed. Disabling the
11:24:36  10:24:35.948 utils.py          ERROR  Slack callback plugin.
11:24:36  Slack callback plugin.
11:24:36  10:24:35.949 utils.py          ERROR  ERROR! Unexpected Exception, this is probably a bug: 'webhook_url'
11:24:36  ERROR! Unexpected Exception, this is probably a bug: 'webhook_url'
11:24:36  to see the full traceback, use -vvv
```

**Comment by TomasTomecek** [comment] 2019-02-28 12:09
Ehm, it seems that Centos CI uses a custom ansible.cfg config where they enable slack callback plugin.

But the root cause really is that prettytable python module is not installed, let me see.

**Comment by TomasTomecek** [comment] 2019-02-28 12:12
What?! It doesn't make any sense, bender is using tabulate, not prettytable.

**Comment by TomasTomecek** [comment] 2019-02-28 12:13
Okay, will try to repro your setup.

**Comment by TomasTomecek** [comment] 2019-02-28 12:57
Bad news: we need to wrap bender in a container: ansible is built against python2 in centos 7 and bender needs python 3, obviously

**Comment by TomasTomecek** [comment] 2019-03-02 09:09
Closing since #80 is fixed.

**Closed by TomasTomecek** 2019-03-02 09:09 UTC
